const SHOP_DATA = [
  {
    title: "men",
    items: [
      {
        shoe_id: "Coffee-1-1",
        name: "Coffee shoe",
        imageUrl: "https://i.postimg.cc/4ygWMS7G/mendress2.png",
        price: 120,
        size: "",
      },
      {
        shoe_id: "BrownMike-2-1",
        name: "Brown Mike",
        imageUrl: "https://i.postimg.cc/ry1nWM3w/mendress3.png",
        price: 150,
        size: "",
      },
      {
        shoe_id: "superior-3-1",
        name: "superior",
        imageUrl: "https://i.postimg.cc/D0PxKPLX/mendress4.png",
        price: 300,
        size: "",
      },
      {
        shoe_id: "BossMan-4-1",
        name: "Boss Man",
        imageUrl: "https://i.postimg.cc/tg8SdT9Y/mensdress5.png",
        price: 480,
        size: "",
      },
      {
        shoe_id: "Red-5-1",
        name: "Red Suede",
        imageUrl:
          "https://i.postimg.cc/0NzXJmRT/maleek-men-dress-shoes-red-suede-af32c9f1-f82a-4335-b6af-9e6ee62cd41b.png",
        price: 120,
        size: "",
      },
      {
        shoe_id: "Addidas-6-1",
        name: "Addidas Style",
        imageUrl: "https://i.postimg.cc/856Z5SQM/addidas1.png",
        price: 80,
        size: "",
      },
      {
        shoe_id: "Addidas-7-1",
        name: "Addidas Props",
        imageUrl: "https://i.postimg.cc/g0rMChgM/addidas2.png",
        price: 78,
        size: "",
      },
      {
        shoe_id: "Addidas-8-1",
        name: "Addidas Classic",
        imageUrl: "https://i.postimg.cc/ZnzVvM4g/arnode1.png",
        price: 95,
        size: "",
      },
      {
        shoe_id: "Mayo-9-1",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/rs5ZhLfM/arnord2.png",
        price: 67,
        size: "",
      },
    ],
  },
  {
    title: "women",
    items: [
      {
        shoe_id: "Mayo-9-10",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/Gpm5z7qF/7.png",
        price: 120,
        size: "",
      },
      {
        shoe_id: "Mayo-9-11",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/QMDTrwR7/8.png",
        price: 125,
        size: "",
      },
      {
        shoe_id: "Mayo-9-12",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/KvKL7nP1/9.png",
        price: 120,
        size: "",
      },
      {
        shoe_id: "Mayo-9-13",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/nzmDqZbC/1.png",
        price: 110,
        size: "",
      },
      {
        shoe_id: "Mayo-9-14",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/HWQMxp9N/2.png",
        price: 50,
        size: "",
      },
      {
        shoe_id: "Mayo-9-15",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/PrTwvB65/3.png",
        price: 58,
        size: "",
      },
      {
        shoe_id: "Mayo-9-16",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/pXCnfq7Y/4.png",
        price: 78,
        size: "",
      },
      {
        shoe_id: "Mayo-9-17",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/MprM4Xzn/5.png",
        price: 128,
        size: "",
      },
      {
        shoe_id: "Mayo-9-18",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/rwpRQ526/6.png",
        price: 168,
        size: "",
      },
    ],
  },
  {
    title: "kids",
    items: [
      {
        shoe_id: "Mayo-9-19",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/Z5j0NnWf/1.png",
        price: 108,
        size: "",
      },
      {
        shoe_id: "Mayo-9-20",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/13W5tdd2/10.png",
        price: 138,
        size: "",
      },
      {
        shoe_id: "Mayo-9-21",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/R0DFPYQK/2.png",
        price: 138,
        size: "",
      },
      {
        shoe_id: "Mayo-9-22",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/brXvP25v/3.png",
        price: 128,
        size: "",
      },
      {
        shoe_id: "Mayo-9-23",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/020Ngj08/4.png",
        price: 158,
        size: "",
      },
      {
        shoe_id: "Mayo-9-24",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/0y5y9vV7/5.png",
        price: 108,
        size: "",
      },
      {
        shoe_id: "Mayo-9-25",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/qBnRLjt6/6.png",
        price: 118,
        size: "",
      },
      {
        shoe_id: "Mayo-9-26",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/W3q4x7XK/7.png",
        price: 118,
        size: "",
      },
      {
        shoe_id: "Mayo-9-27",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/2y4SSSp7/8.png",
        price: 118,
        size: "",
      },
      {
        shoe_id: "Mayo-9-28",
        name: "Mayo J",
        imageUrl: "https://i.postimg.cc/dtY0SrdH/9.png",
        price: 98,
        size: "",
      },
    ],
  },
];

export default SHOP_DATA;
